version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.4GB'

  api1:
    build: .
    hostname: api1
    depends_on:
      - db
      - redis
    ports:
      - '81:3000'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.4GB'

  api2:
    build: .
    hostname: api2
    depends_on:
      - db
      - redis
    ports:
      - '82:3000'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.4GB'

  redis:
    image: redis
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9999:9999'
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
