version: '3.4'

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'PGUSER=postgres', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'

  api1: &api
    build: .
    hostname: api1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - '3000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9999:9999'
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
